### ISSUE TITLE
You should be able to use Parinfer with the Atom editor

### ISSUE THREAD

**Issue by oakmac** [oakmac/atom-parinfer#1]
[Parinfer] is a novel way of editing LISP code that infers code structure from common indentation conventions.

[Atom] is a popular, modern text editor built on top of web technologies and designed for extension.

You should be able to use Parinfer when editing Lisp code in Atom.

[Parinfer]:http://shaunlebron.github.io/parinfer/
[Atom]:https://atom.io/

**Comment by martinklepsch** [comment]
I think this can be closed :stuck_out_tongue: Great work @oakmac!

**Comment by oakmac** [comment]
Thanks :)

I like to use "Issue #1" to describe the higher-order purpose of the project. Similar to the Ubuntu project's [Bug #1](https://bugs.launchpad.net/ubuntu/+bug/1).

I agree this can be closed now.
