### ISSUE TITLE
Better UX when running Paren Mode first time

### ISSUE THREAD

**Issue by oakmac** [oakmac/atom-parinfer#18]
atom-parinfer automatically runs Paren Mode on any file it recognizes when it is first loaded into the editor. see [Fixing existing files](http://shaunlebron.github.io/parinfer/#fixing-existing-files) for more information on why this is a essential step.

This is always a "safe" operation in that it will not change the structure of your code, but it might make lots of changes to your indentation resulting in a large diff.

Right now this happens silently and then drops the user into Indent Mode. It is unacceptable for an extension to make potentially large modifications to your files without your permission. Some sort of modal or "Are you sure you want to do this?" dialog should confirm the user's intention to change their file.

If they say "yes", Paren Mode makes it's changes and things continue as normal.
If they say "no", no changes are made and Parinfer disables itself until turned on.

**Comment by victor-acuna** [comment]
I started to implement a very simple dialog for warning the user before Paren mode is run on a newly opened file, but I ran into a question: should the dialog pop up every time a parinfer-compatible file is opened? Or should it only prompt the user if the file is determined to be in need of fixing?

I couldn't see any immediate way to figure out if a file needs Paren mode run on it without actually running Paren mode first. Even then, the output of Paren mode would have to be checked against the old text somehow. It might help to either make that check easier (and faster) so that the dialog will only pop up when it is needed.

**Comment by oakmac** [comment]
> I started to implement a very simple dialog for warning the user before Paren mode is run

Awesome :) I didn't look too far into this, but I think Atom provides some built-in mechanisms for standard dialogs like this. Would prefer to use those in place of something custom if possible.

> Or should it only prompt the user if the file is determined to be in need of fixing?

I think it should only prompt if the file needs to be changed. Once you start using Pariner regularly most of your files should be unchanged by Paren Mode anyway.

> I couldn't see any immediate way to figure out if a file needs Paren mode run on it without actually running Paren mode first.

I think you'll have to run Paren Mode on the file. The only other idea I can think of is for Parinfer to keep a history of file content hashes after Parinfer runs so that it can recognize when a file does not need Paren Mode to be run. Seems like a pretty complex solution compared to just running Paren Mode again.

**Comment by oakmac** [comment]
Also see [Issue #30](https://github.com/oakmac/atom-parinfer/issues/30) (assuming that Paren Mode is the speed culprit for that issue) - it would be nice if the user were somehow aware when Paren Mode was running or if it could be done dynamically per tab as they are focused.

I punted on all these ideas initially just due to additional complexity.

**Comment by victor-acuna** [comment]
Ah, when I meant "implement a very simple dialog" I meant just using the built-in Atom one. It was very straightforward.

So does running Paren Mode return anything special if there are no changes to the file? Seemed to me like parinfer was always going to return the full body of text with any changes made in-place. Would I really just have to diff the old text and the new text to determine any changes?

**Comment by oakmac** [comment]
> Would I really just have to diff the old text and the new text to determine any changes?

I believe this is the right approach.

@shaunlebron may have an opinion here as to whether or not a boolean `textChanged` property would be appropriate to add to the result returned from the core Parinfer library?

**Comment by shaunlebron** [comment]
> Would I really just have to diff the old text and the new text to determine any changes?

yes. parinfer has to process the full text to determine if it needs changes.  checking the diff would give you the answer.
