### ISSUE TITLE
Run Paren Mode on whole directory

### ISSUE THREAD

**Issue by oakmac** [oakmac/atom-parinfer#21]
There should be an option in the Parinfer package menu to run Paren Mode on a whole directory recursively.

The idea here is that you want to start using Parinfer on your project, so you run Paren Mode once on all of your files to generate a single commit that has all the indentation changes.

**Comment by rgdelato** [comment]
@oakmac Has this use case already been covered by [Parlinter](https://github.com/shaunlebron/parlinter)?

**Comment by oakmac** [comment]
Yes :)
