### ISSUE TITLE
Settings Button Not Visible

### ISSUE THREAD

**Issue by ivanreese** [oakmac/atom-parinfer#25]
I've installed atom-parinfer, but I'm not able to see the Settings button when I view it in the packages list — just Uninstall and Disable.

<img width="687" alt="screen shot 2015-11-17 at 9 51 34 pm" src="https://cloud.githubusercontent.com/assets/2061924/11232945/693d2478-8d75-11e5-8f20-7d777661b8fc.png">

I've restarted Atom, and disabled/reenabled the package.

Please, let me know what I'm missing — I'll don the dunce cap and sit in the corner after showering you with praise!

**Comment by oakmac** [comment]
Hi Ivan - atom-parinfer does not have any settings right now.

Looks normal to me. No dunce cap necessary ;)

**Comment by ivanreese** [comment]
Ahhhhhhhh nope, dunce cap is totally necessary. In the docs you say:

"You can edit these file extensions by going to Packages --> Parinfer --> Edit File Extensions in the menu."

I read "menu" as "settings".

:tophat:
:blush:

**Comment by ivanreese** [comment]
Almost forgot the praise — THANK YOU!!!

This project has me boundlessly excited.

**Comment by oakmac** [comment]
Thanks for the kind words :)

Parinfer is very exciting! I've been loving using it the last week or so.

cc @shaulebron
