### ISSUE TITLE
Highlight ending brackets as fainter, like in Parinfer’s demo

### ISSUE THREAD

**Issue by roryokane** [oakmac/atom-parinfer#26]
Ending brackets/parens should be syntax-highlighted to be fainter/dimmer, the way they look on [Parinfer’s site](https://shaunlebron.github.io/parinfer/). For example, in

```clojure
(defn component []
  (html
    [:div {:style {:background "#FFF"
                   :color "#000"}}
      [:h1 "title"]]))
```

All occurrences of `)`, `]`, and `}` should be light gray instead of black against the white background.

This highlighting would be useful because it reduces visual noise. It also makes the auto-insertion of brackets more predictable, because you can see which characters are fixed in place (opening brackets) and which will be moved as necessary (closing brackets).

The dimming shouldn’t clash with the background, no matter what colors the user is using for their theme. Parinfer’s site accomplishes this by applying `opacity: 0.4` to those characters and not specifying a color.

**Comment by oakmac** [comment]
I know @shaunlebron choose to do this on the website for demonstration purposes.

I'm not sure if this is something I would want to see full-time in an editor. Let me give it some thought.

At a minimum, this could be turned on / off with a setting.

**Comment by shaunlebron** [comment]
Thanks, @roryokane. I do consider this important for all the reasons you stated.  I would enable it by default in Indent Mode, and disable it during Paren Mode.

Not sure how to do this in Atom, but I had to customize CodeMirror's clojure tokenizer to attach a css class to these inferred parens, [code here](https://github.com/shaunlebron/parinfer/blob/bdc0d37d59195722313127f4defea2998174c956/resources/public/codemirror/mode/clojure/clojure-parinfer.js#L248-L257)

**Comment by oakmac** [comment]
Just took a quick glance at doing this in Atom; it might be pretty tricky to only target the inferred parens (as opposed to all expression-ending symbols).

Will need to investigate further.

**Comment by oakmac** [comment]
This might be helpful:
https://github.com/atom/language-clojure/commit/b94b61b54ca09926a6760a409b93e3fb6a44e1c1

Pretty sure we will need to add "end" tags for all expressions in order to get this working via CSS. Still not sure how to handle "only inferred parens" as opposed to "all expression ending parens".

**Comment by shaunlebron** [comment]
I modified the clojure grammar to identify paren trails here: https://github.com/shaunlebron/language-clojure/commit/7437ce7cdc037aede0bef70486912ff0349f8e85

it adds a `paren-trail` class to relevant close-parens, while still respecting existing grammar rules.  will submit PR soon if you guys think this looks okay.

gif showing Before and After `.paren-trail { opacity: 0.3; }`:

![gif](http://i.imgur.com/gLlW7fB.gif)

**Comment by oakmac** [comment]
Awesome work Shaun :)

**Comment by shaunlebron** [comment]
to make this work for multiple lisp grammars without modifying every single one, we should probably look into using decorated markers.  [example](https://github.com/richrace/highlight-selected/blob/master/lib/highlighted-area-view.coffee#L118-L120)

**Comment by shaunlebron** [comment]
This is finally on by default as of Atom 1.9, just released.

**Comment by Misophistful** [comment]
I was surprised and disappointed to see darker end brackets after updating to Atom 1.9, and it took me a long time to figure out that it was this change in Parinfer causing it.

I reverted it by adding:
```
atom-text-editor::shadow {
  span.punctuation.section.end.trailing.clojure {
    opacity: 1;
  }
}
```
to my `styles.less` file.

However, I don't think forcing all Parinfer users to do this is the right approach. Is there still a plan to add a setting for this?

**Comment by roryokane** [comment]
@Misophistful [@shaunlebron recommended](https://github.com/oakmac/atom-parinfer/issues/26#issuecomment-158667517) having this style active by default in Indent mode but off by default in Paren mode. Would implementing just that solve your problem? That is, is the reason you don’t want to see fainter end brackets because you use Paren mode?

If so, I suggest implementing mode-sensitive faintness, and not bothering to implement a user setting for faintness unless it is requested. That would keep the user interface simple by still having no settings for Parinfer, and I expect that that default would match when all users want this setting.

**Comment by Misophistful** [comment]
@roryokane I don't understand the value that fainter closing brackets adds to either of the modes in Parinfer. Could you explain how it helps you? (To my eyes, the fainter brackets only make the code look unbalanced.)

I use Indent mode, almost exclusively, so having it enabled by default in that mode would not solve my issue, and I'd still need to force it off in my `styles.less`.

I'd argue that a 'functionality' package, such as Parinfer, shouldn't be forcing an editor rendering change on all its users.

**Comment by roryokane** [comment]
@Misophistful

> I don't understand the value that fainter closing brackets adds to either of the modes in Parinfer. Could you explain how it helps you?

I find this styling helpful in Indent mode. I’m not really sure whether I find it helpful in Paren mode.

The reasons for this feature I gave in [my original request](https://github.com/oakmac/atom-parinfer/issues/26#issue-118209937):

> This highlighting would be useful because it reduces visual noise. It also makes the auto-insertion of brackets more predictable, because you can see which characters are fixed in place (opening brackets) and which will be moved as necessary (closing brackets).

To elaborate:

### Visual noise

Over my time working with Lisps, I developed the mindset that ending brackets are visual noise. They are like end-of-line semicolons `;` in Java and JavaScript: necessary for the parser, but irrelevant to the human – assuming the codebase is indented correctly. And Parinfer removes the concern that the codebase won’t be indented correctly. I don’t want to have to pay attention to these irrelevant characters.

When closing brackets are dimmed, it is slightly easier to scan my eyes from the end of the line to see what the last actual word in that line of code is:

```clj
          :some-long-key ["too" "much" "code" "to" "read" "from" "the" "beginning" "hamster"]}}}))
```

So if the ending brackets `]}}}))` are dimmed, I can more easily see that the line ends with `"hamster"`.

### Predictability

When the closing brackets are dimmed in Indent mode, I find that a useful reminder that the closing brackets act like “virtual” brackets that can move at any time. If I have this code:

```clj
(def config
  {:enabled true})
```

and I plan to add another line containing `:size 13`:

```clj
(def config
  {:enabled true
   :size 13})
```

The fact that the end-of-line `})` was always dimmed serves to reduce my surprise when those characters are moved for me. From the looks of the characters, I can remember that only the `(` and `{` I typed are significant.

**Comment by Misophistful** [comment]
@roryokane Thanks for the explanation - all of your points make sense to me.

I'm actually going to try turning the fainter brackets back on, and see if I can get used to it. I like your suggestion to have the fainter brackets on for Indent mode, and off for Paren mode. It would act as another visual indicator of which mode you're in.

I think my strong initial distaste for the dimming came from it being enabled automatically after an Atom update, without me understanding why it was happening. Though I'd guess there'll be users who won't like Parinfer altering their bracket rendering even after understanding why it's happening, and that adding it as a package option makes sense. But I'm open to being convinced that this assumption is incorrect.

**Comment by oakmac** [comment]
FYI - Inferred parens are only dimmed in Indent Mode with [Commit #5c6514a2]

Will be in the next release.

cc: @Misophistful @roryokane 

[Commit #5c6514a2]:https://github.com/oakmac/atom-parinfer/commit/5c6514a220fac63e009b38bb7bf580016fd48b0f
