### ISSUE TITLE
get rid of underscore

### ISSUE THREAD

**Issue by narma** [oakmac/atom-parinfer#28]
Why bundle big js library like underscore for only one function like `_.debounce`?

```clojure
(defn debounce 
  ([f] (debounce f 1000))
  ([f timeout]
    (let [id (atom nil)]
      (fn [evt]
        (if (not (nil? @id))
          (js/clearTimeout @id))
        (reset! id (js/setTimeout
                   (partial f evt)
                   timeout))))))
```

**Comment by narma** [comment]
Just thought, anything what underscore does possible to implement with clojurescript, especially that clojurescipt main library already implements at least half of that. underscore just not needed with this powerfull language like clojurescript.

**Comment by oakmac** [comment]
thanks :)

FYI - The Google Closure Library provides `goog.functions.debounce` (see [here](https://github.com/google/closure-library/blob/a8e53cfcf0740faefb754f653dd81667df8cffe2/closure/goog/functions/functions.js#L379-L391)), but not in the current version of ClojureScript.
