### ISSUE TITLE
Parinfer deletes comma upon opening Racket file

### ISSUE THREAD

**Issue by otherjoel** [oakmac/atom-parinfer#29]
See the change to line 140 in [this commit](https://github.com/otherjoel/try-pollen/commit/689926d3638afefb278ee4b6a564426c1042bfda). This can be recreated by adding in the comma, closing the file, and re-opening it in Atom. (I have the package set to include `.rkt` in its list of recognized extensions.) I am using Atom 1.1.0 and Parinfer 0.8.1 on Mac OS X El Capitan.

The comma in question is common Racket shorthand for the `unquote` function in a [quasiquote](http://docs.racket-lang.org/reference/quasiquote.html) context. Deleting the comma thus introduces errors.

I did not realize before this that any operation of Parinfer would affect any characters besides parens, brackets and whitespace.

**Comment by oakmac** [comment]
paging @shaunlebron on this; think it might be more of a Parinfer library question than related to the Atom plugin

**Comment by shaunlebron** [comment]
@otherjoel sorry about that!  Clojure treats commas as whitespace, so I'm guessing that it removed commas that appeared at the start of a line after some indentation:

```
(defn foo [a b]
   ,(+ a b))
```

Is that correct?  (Tracking this bug here: https://github.com/shaunlebron/parinfer/issues/61)

**Comment by shaunlebron** [comment]
oh, I just looked at your diff and answered my own question.  nvm, fix coming

**Comment by otherjoel** [comment]
Thanks, Shaun! No worries I know Parinfer is still under construction :)

The DrRacket IDE indents such cases as shown below. I took a look at [shaunlebron/parinfer#61](https://github.com/shaunlebron/parinfer/issues/61) and it looks to me like the change you propose will result in identical treatment (which is good).

~~~~racket
(define (make-link x)
  `(a [[href "#top"] [class "internal"]]
      ,(splice x)))
~~~~

**Comment by shaunlebron** [comment]
Released parinfer 0.2.3 with this fix, and added some [test cases](https://github.com/shaunlebron/parinfer/commit/ac3911a48c3a99c079b2853738c0678e7f58bb57#diff-5ff5d0a24786756872c3119325d5e3cdR446).

updated atom-parinfer's dependency, but I'll let @oakmac publish the plugin update.

Glad to see a Racket user :)  Thanks for the bug report!

**Comment by oakmac** [comment]
Thank you for the quick resolution on this @shaunlebron :)

**Comment by oakmac** [comment]
FYI - Pushed this fix into v0.9.0

**Comment by otherjoel** [comment]
Thank you both for your help and for such a helpful tool!

**Comment by otherjoel** [comment]
Just to let you know, updating to v0.9.0 of the plugin has not removed the issue for me. You can test with the file in the commit I linked above. Is there something else I should be doing/updating?

**Comment by shaunlebron** [comment]
I just tried it and experienced the same problem until I closed all tabs and restarted Atom.  To test, I opened a file called `test.rkt` with the following text:

```racket
(define (make-link x)
  `(a [[href "#top"] [class "internal"]]
      ,(splice x)))
```

**Comment by otherjoel** [comment]
Ah, closing all tabs was something I hadn’t thought of. Doing that and restarting Atom fixed it for me as well. Thanks!
