### ISSUE TITLE
Option to configure file modification warning

### ISSUE THREAD

**Issue by damassi** [oakmac/atom-parinfer#34]
For new projects I get a warning every time I open the file for the first time. It would nice to be able to toggle this on and off via a checkbox and implicitly trust the plugin.

**Comment by oakmac** [comment]
I like this idea. I thought about it when I wrote the notification part but just didn't get around to it.

**Comment by damassi** [comment]
Yeah, the file popup reminds me of word : ) Another option would be to add in a toggle for disabling further warnings.

**Comment by oakmac** [comment]
Just pushed a fix for this. If you create a `.atom-parinfer-config.json` file in your homedir you can disable the prompts.

```js
{
  "show-open-file-dialog?": false
}
```

**Comment by oakmac** [comment]
Fixed in [v1.4.0](https://github.com/oakmac/atom-parinfer/releases/tag/v1.4.0) :)
