### ISSUE TITLE
Does not work with CRLF line ending

### ISSUE THREAD

**Issue by ghalle** [oakmac/atom-parinfer#36]
Just tried using this package and it was behaving very oddly, after making an edit it would either do nothing or spam newlines under the edited line.

I changed the line ending in atom to LF and everything works fine now.

**Comment by shaunlebron** [comment]
Thanks for reporting!  :+1: I just published `parinfer 1.3.0` to fix this in the core library, so @oakmac will have to update the plugin to use it.

**Comment by oakmac** [comment]
This should be fixed with [v1.3.0](https://github.com/oakmac/atom-parinfer/releases/tag/v1.3.0)
