### ISSUE TITLE
Allow tabbing through confirmation dialogs

### ISSUE THREAD

**Issue by martinklepsch** [oakmac/atom-parinfer#45]
Dialogs like [this one](https://github.com/oakmac/atom-parinfer/blob/1ea76498ddf098acae7ddf9f325a40700767d97b/src-cljs/atom_parinfer/core.cljs#L378) always require mouse action (as far as I can tell). Maybe the buttons can be focused so users can tab through them or maybe there's another keyboard friendly way to implement those dialogs.

**Comment by oakmac** [comment]
FYI - you can disable those dialogs with a [config file](https://github.com/oakmac/atom-parinfer/issues/34#issuecomment-170146141)

Not sure if the Atom API allows you to focus the buttons in those dialogs or not. It would be nice if they were keyboard-accessible.

**Comment by martinklepsch** [comment]
The issue with that is that most of the time I'm pressing "no", which this option won't help me with if I understood correctly. I guess I should go through the project once and do a whitespace cleanup then maybe this will be solved.

**Comment by oakmac** [comment]
Ahh, I see.

Atom-parinfer is definitely optimized for the use case of "I always want to be using Parinfer for Lisp files."

The feature described in [Issue #21] would help you with doing all the whitespace cleanup at once.

The feature described in [Issue #5] would help with the use case of flagging certain files as "do not use Parinfer on this file."

[Issue #5]:https://github.com/oakmac/atom-parinfer/issues/5
[Issue #21]:https://github.com/oakmac/atom-parinfer/issues/21

**Comment by naartjie** [comment]
> Dialogs like this one always require mouse action

@martinklepsch on mac OS X you can make all dialog's keyboard-accessible: `System Preferences > Keyboard > Shortcuts`

Select `All Controls`

<img width="590" alt="screen shot 2016-06-03 at 16 04 10" src="https://cloud.githubusercontent.com/assets/514563/15781141/077c77a8-29a5-11e6-83ec-469d04aadd64.png">

You will then be able to press <kbd>Space</kbd> for *No* and <kbd>Enter</kbd> for *Yes*, or <kbd>Tab</kbd> if you have more options.

It's still not ideal, and I wish there was a way to disable Parinfer from doing it's magic all together (maybe on a per project level). I like it for my own files, but I find it unbearable when working on bigger projects with others who don't feel the same about strict formatting rules.

@oakmac do you think it would make sense to have another setting for this? Something like `disable?` `true`, next to #34's `show-open-file-dialog?`?

**Comment by oakmac** [comment]
@naartjie If you want atom-parinfer to be "off" by default (but still installed), you can remove all of the file extensions from the `.parinfer-file-extensions.txt` file. Then manually turn it on for the files you want using <kbd>Ctrl</kbd>+<kbd>(</kbd>

**Comment by naartjie** [comment]
@oakmac Thanks for the tip!!

**Comment by oakmac** [comment]
> I guess I should go through the project once and do a whitespace cleanup then maybe this will be solved.

The [parlinter](https://github.com/shaunlebron/parlinter) project might help with this :+1:
