### ISSUE TITLE
Balancing bug

### ISSUE THREAD

**Issue by Krajsnick** [oakmac/atom-parinfer#46]
Hi, quite new to Clojure, so first this might be my own fault.

When working through the Clojure Koans third file, about lists parinfer is giving me a headache. Parinfer ends the `try` form and I'm unable to erase the paren. I have provided a gif, please take a look. Parinfer shows Indent mode in the status bar. Is this caused by having the `try` expression on the same line as the start `=` form?

![parinfer-bug](https://cloud.githubusercontent.com/assets/979555/12927606/46332f1e-cf69-11e5-86f3-44e62bbddb1c.gif)

**Comment by oakmac** [comment]
Thanks for posting this issue with the gif; very helpful for understanding.

I'm happy to report that you are not crazy, and this is Parinfer working as expected :)

In [Indent Mode], Parinfer will automatically balance all parens based on **indentation**. Think of indentation as the master, and paren structure as the slave. In your example, as you're typing the string `"No Dice!"`, you can see Parinfer automatically add a closing paren on Line 39 as soon as the opening paren in front of `(try` vertically aligns with the opening paren in front of `(pop` on line 37.

In [Paren Mode], the paren structure is the master and indentation is the slave. Try this same example using Paren Mode and you will see lines 37-39 automatically adjust as you type the string.

I hope this explanation is helpful. The [Parinfer website] goes into more detail.

[Indent Mode]:https://shaunlebron.github.io/parinfer/#indent-mode
[Paren Mode]:https://shaunlebron.github.io/parinfer/#paren-mode
[Parinfer website]:https://shaunlebron.github.io/parinfer/

**Comment by Krajsnick** [comment]
Thanks for this in-depth explanation. I see that I must learn how the parinfer works, just installed it because the community said it was mandatory for Clojure development ;)

Awesome plugin keep the good work up!

**Comment by oakmac** [comment]
You're most welcome. Good luck with your Clojure adventure. You've made a considerably wise decision ;)
