### ISSUE TITLE
Parinfer question

### ISSUE THREAD

**Issue by oakmac** [oakmac/atom-parinfer#51]
FYI - @phillc73 and @otherjoel, I moved your conversation to this new Issue since it was unrelated to Issue #9. Thanks :)

@phillc73 's original question:

-----------------------------------------------

Just starting out with Clojure (first attempt at any Lisp language) so I hope this is not user error and I'm posting in the right Issue.

Following the "do" example in the [Brave and True Clojure book](http://www.braveclojure.com/do-things/), Parinfer in Atom wants to do this:

```Clojure
(if false
  (do (println "Yes! True!")) 
  "True"
  (do (println "No")) 
  "False")
```
Rather than:

```Clojure
(if false
  (do (println "Yes! True!")
  "True!")
  (do (println "No")
  "False"))
```

**Comment by oakmac** [comment]
@otherjoel 's response:

-------------------------------------------------

> Parinfer in Atom wants to do this [...] rather than this [...]

Yes, this is expected/desired behaviour. Because `"True"` in your example is at the same indent level as the line above it. So Parinfer reasons they must be siblings in the list and adjusts parentheses to reflect this. (same goes for your `"False"` line.)

If you indent `"True"` any further past the indent level of the line above it, Parinfer will see that it is supposed to be a sibling of `(println "Yes! True")` instead of a sibling of `(do ...)` and it will make the parenthses reflect this. Note that this is how the indentation appears in [the original example](http://www.braveclojure.com/do-things/#do) from the book you linked.

The above assumes you're in Indent Mode (where you change indentation manually/directly and Parinfer handles the parens in the background, matching them to the indentation).

**Comment by oakmac** [comment]
Also wanted to add that 1) this is a great question, and 2) @otherjoel 's answer is spot on

You may want to look at Issue #46 as well.

**Comment by phillc73** [comment]
Thanks. I see now. Looks like it was user error, so might be just best to close. I still have a lot of reading to do!

**Comment by oakmac** [comment]
No worries; you won't regret learning Clojure :)

If you haven't checked out the [main Parinfer page](https://shaunlebron.github.io/parinfer/), that might be worth doing. The short version is that Parinfer is just an editing mode for your editor that helps you write Lisp code by balancing parenthesis based on indentation (like Ruby or CoffeeScript). It doesn't fundamentally change the language or syntax; it's just a "human helper" ;)

**Comment by phillc73** [comment]
@oakmac I've spent a lot of time in debugging hell using [RStudio's Shiny Web Framework](http://shiny.rstudio.com/) where mismatched parenthesis are the number one cause of application errors.

When I was investigating which language to explore next, and read about Parinfer, it was a massive plus for Clojure.

**Comment by oakmac** [comment]
> When I was investigating which language to explore next, and read about Parinfer, it was a massive plus for Clojure.

I'm sure @shaunlebron will be glad to hear that :)

**Comment by otherjoel** [comment]
👍🏻
