### ISSUE TITLE
After toggling to paren mode, closing the file and opening a new one immediately changes to indent mode

### ISSUE THREAD

**Issue by indigo0086** [oakmac/atom-parinfer#55]
This has happened only recently. Steps to reproduce.  

2. Open a file matching an extension for parinfer to activate.
3. Switch to paren mode (on my editor the default is indent)
4. Close the file and open a new one.

Expected: The file should be opened in paren mode
Actual: The file opens in indent mode, this will happen consistently.

**Comment by oakmac** [comment]
Just curious - why did you close this issue?

Sorry I never replied originally. It is the default behavior to open files in Indent Mode (unless initially applying Paren Mode fails). I suppose you could make the case for persisting which mode files are in between sessions, but I suspect most users want to be in Indent Mode most of the time.

**Comment by indigo0086** [comment]
Sorry, I glossed over the modes parinfer goes in when opening a file and assumed that it should be sticky, and I actually forgot that indent mode is the one I had been using mostly.
