### ISSUE TITLE
Bad layout of let-expressions (or: contradicting the user)

### ISSUE THREAD

**Issue by stugol** [oakmac/atom-parinfer#57]
The following code is wrongly handled:
```
(let ((result (catch 'fail
  (loop for code in content do
    (eval code))
  nil))))
```
Leading to:
```
(let ((result (catch 'fail)))
    (loop for code in content do
      (eval code))
    nil)
```
Which of course is not what I intended. To work around this, I need to introduce redundant line breaks:
```
(let
  ((result
    (catch 'fail
      (loop for code in content do
        (eval code))
      nil))))
```
What _should_ happen, is that when I delete the closing paren after `'fail`, it is automatically added to the end. And if I then type the closing paren after `'fail`, the extra paren is removed from the end. In short, I should be able to override the paren placement. The plugin should never delete a paren _that I have just typed!_ If I explicitly type it, then I obviously want it there! If the parens are then imbalanced, one should be removed that I have _not_ explicitly typed.

One way you could achieve this, is by assigning a hidden timestamp to every paren typed (or deleted!) by the user. If the expression is not balanced, and parens need to be added or removed, try to find somewhere to add them that has not already been adjusted by the user - or, failing that, prefer to overwrite earlier adjustments rather than later ones.

**Comment by shaunlebron** [comment]
Thanks for reporting, @stugol. Child lines must be to the right of their containing open-paren.  Otherwise it would be ambiguous which open-parens should be closed based on indentation.  Your example is fixed with further indenting:

```
(let ((result (catch 'fail
                (loop for code in content do
                  (eval code))
                nil))))
```

**Comment by shaunlebron** [comment]
@stugol: What dialect of Lisp is this that uses that indentation convention?  When designing Parinfer, I was hoping to following the common indentation conventions, but this one is new to me.

**Comment by stugol** [comment]
Uh....mine ;)

Are you saying that it's _generally accepted_ to write lisp with the large indentation you just illustrated? People don't write it the other way?

**Comment by stugol** [comment]
In any event, there is a problem with constructs like `let ((`:
```
let ((a 1)
      (b 2))
```
The opening paren `(b` needs to be precisely aligned with `(a`, to avoid the aforementioned problem. However, code is generally indented with tabs (or, alternatively, more than one space). So I'd need to do something like this:
```
let (   (a 1)
         (b 2))
```
Because the second opening paren does not happen to lie on an indentation boundary. This is ugly.

**Comment by shaunlebron** [comment]
> Are you saying that it's generally accepted to write lisp with the large indentation you just illustrated? People don't write it the other way?

Generally not.  It goes against the two main rules of thumb here: http://c2.com/cgi/wiki?LispIndentation

I used to break these rules sometimes to reduce indentation or whatever, but keeping consistent rules is what allows Parinfer to automate close-paren positions based on indentation.

Regarding your `let ((` example, the first form looks good, but I don't understand anything you said after the "However" part.

**Comment by stugol** [comment]
I mean, code is generally indented with tabs, or at least a number of spaces - such as 3 - to simulate tabulation:
```
if ...
|  if ...
|  |  print ...
|  |  |
|  |  |    <-- tab columns for illustration

(code
|  (code
|  |  (code)))
|  |  |
|  |  |    <-- tab columns for illustration
```
But to correctly indent within **one** of a pair of adjacent parens, I'd need to indent all my lisp code with a single space:
```
(code
 (code
  (code)))     <-- not indented with tabs!

let ((a)
|    (b))      <-- not indented with a tab!
|  |  |
|  |  |        <-- tab columns for illustration (not used here!)
```
So... is lisp always supposed to be indented with single spaces?

**Comment by oakmac** [comment]
@stugol - Have you read through the main [Parinfer explanation site]? I think it might address some of your questions here.

[Parinfer explanation site]:https://shaunlebron.github.io/parinfer/

**Comment by shaunlebron** [comment]
@stugol: I see what you're saying now.  Snapping to different tab stops does allow code to be indented more easily.  Lisp (and thus Parinfer) doesn't work well tab characters though. By definition, indentation lengths become ambiguous when using tabs, and remember we need consistency, not ambiguity, for Parinfer's automation to work.

But this problem has been solved in other editors using Parinfer, like Cursive and I believe Night Code.  See this video of Cursive at 0:49 to see what I mean: https://youtu.be/mqjDOSKyIcc?t=49s

Ideally, atom-parinfer would also map <kbd>Tab</kbd> and <kbd>Shift</kbd>+<kbd>Tab</kbd> to snap the cursor to these critical points via space-insertion/removal, but this is not implemented yet.  Parinfer's core API has recently been updated to provide information for doing this on a given line, so there is a path to implementing this reliably here.

**Comment by stugol** [comment]
@oakmac Thanks, I'll look into that.

@shaunlebron So essentially, dynamically-sized tab stops? Sounds great. Any hope for this soon?

**Comment by stugol** [comment]
Incidentally, from the explanation:
> As a visual cue, we slightly dim these parens to signify their inferred nature.
Nope. Not on my screen they ain't! :(

**Comment by oakmac** [comment]
> As a visual cue, we slightly dim these parens to signify their inferred nature.

Dimming inferred closing parens is being tracked at [Issue #26](https://github.com/oakmac/atom-parinfer/issues/26)
