### ISSUE TITLE
Preserve indentation when Paren Mode not working on backspace

### ISSUE THREAD

**Issue by mauricioszabo** [oakmac/atom-parinfer#58]
There's a problem with the paren-test in Parinfer: https://shaunlebron.github.io/parinfer/

Look at the last example. When we delete characters from `my-map`, it de-indents the map. In Atom with this plugin, this is not happening - it only keeps indentation when typing.

**Comment by oakmac** [comment]
This is tracked at [Issue #15](https://github.com/oakmac/atom-parinfer/issues/15)
