### ISSUE TITLE
Add option to turn off prompt to "edit file"

### ISSUE THREAD

**Issue by webfella** [oakmac/atom-parinfer#61]
I'd like to have an option in the settings to turn off this prompt.

<img width="440" alt="parinfer" src="https://cloud.githubusercontent.com/assets/1121418/15932970/cb71a216-2e2b-11e6-8673-2c500193160f.png">

It's great on my personal projects, but at work where our style might not exactly match the indent setting it's not great to have to hit no every time I open a new file.

**Comment by oakmac** [comment]
You can prevent the dialogs from showing using a config file as [described here](https://github.com/oakmac/atom-parinfer/issues/34#issuecomment-170146141).

However, regardless of the dialog Parinfer will not enter into Indent Mode without first running Paren Mode on the file. Please see [Fixing Existing Files](https://shaunlebron.github.io/parinfer/#fixing-existing-files) for more information on why it has to work this way.

**Comment by webfella** [comment]
Awesome, thanks @oakmac.

I understand that I'll lose Indent mode at work, will just have to live with it on the shared projects. Cheers.
