### ISSUE TITLE
add option to disable auto parinfer

### ISSUE THREAD

**Issue by ItamarShDev** [oakmac/atom-parinfer#63]
when opening a file a message shown giving you the option to "fix" the file
most of the times, on big files, the parifner fails and the code gets messed up.

adding an option not to auto fix the files would be great

**Comment by oakmac** [comment]
Do you have an example file that Parinfer fails to fix correctly?

**Comment by oakmac** [comment]
To add some context here:

If you have an example of a Lisp file with balanced parens that atom-parinfer does not correctly indent - ie: "the code gets messed up" - then that would be a pretty serious error in [parinfer.js]. I'm sure @shaunlebron would be interested to examine such a file.

If the concern is over not formatting the file immediately on load, then you might wish to disable Parinfer by default via file extension config ala [Issue #61](https://github.com/oakmac/atom-parinfer/issues/61).

[parinfer.js]:https://github.com/shaunlebron/parinfer/tree/master/lib

**Comment by shaunlebron** [comment]
@ItamarShDev an example would be appreciated
