### ISSUE TITLE
Do not dim close-parens when Parinfer is disabled

### ISSUE THREAD

**Issue by shaunlebron** [oakmac/atom-parinfer#65]
_related to https://github.com/oakmac/atom-parinfer/issues/26_

Right now, the following styles are applied to all clojure files even when Parinfer is disabled:

```sass
atom-text-editor::shadow {
  span.punctuation.section.end.trailing.clojure {
    opacity: 0.4; // <-- desired opacity of trailing parens
  }
}
```

Perhaps we can add a classname to the text editor only when Parinfer is enabled (and only in indent mode), and then use that classname in the above selector.

**Comment by oakmac** [comment]
I like this idea. I was already thinking of doing this re: Issue #26 :)
