### ISSUE TITLE
Highlight closing parens in red when unbalanced?

### ISSUE THREAD

**Issue by oakmac** [oakmac/atom-parinfer#66]
Had this thought while working on Issue #65.

It is possible for the user to create imbalanced parens (ie: code that will not compile) when in Paren mode. Currently we [turn the status bar red](https://github.com/oakmac/atom-parinfer/blob/5c6514a220fac63e009b38bb7bf580016fd48b0f/src-cljs/atom_parinfer/core.cljs#L142-L157) when unbalanced parens are detected in Paren mode.

Now that we have the grammar and CSS selector for closing parens, we could also highlight closing parens in red as another visual indicator of this condition.

**Comment by shaunlebron** [comment]
Need to highlight unmatched close-parens in Indent Mode too for Parinfer >= 2.0.0, for the following example.

```
(let [{:keys (|} {:foo :bar}] foo)
               ^            ^      
               Suddenly unmatched after inserting the `(` before the cursor...
               Removing them (as I did in Parinfer 1.X) was messed up...
               Best to do nothing (and highlight unmatched) until we find something better.
```

**Comment by shaunlebron** [comment]
this is done
