### ISSUE TITLE
Atom 1.13.0 warns that Parinfer is using a deprecated selector

### ISSUE THREAD

**Issue by whitecoop** [oakmac/atom-parinfer#73]
![selector-warning](https://cloud.githubusercontent.com/assets/10946864/21859022/f06cb7c8-d7df-11e6-9911-e987489aa8ad.PNG)

Text:
> Parinfer\styles\atom-parinfer.less
>
> Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:
> - `atom-text-editor.indent-mode-76f60::shadow span.punctuation.section.end.trailing.clojure` => `atom-text-editor.indent-mode-76f60.editor span.syntax--punctuation.syntax--section.syntax--end.syntax--trailing.syntax--clojure`
>
> Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by oakmac** [comment]
Thanks for the report :+1: 

This should be fixed with v1.17.0
