### ISSUE TITLE
Deprecated selector in `Parinfer/styles/atom-parinfer.less`

### ISSUE THREAD

**Issue by nico-schneider** [oakmac/atom-parinfer#74]
In `Parinfer/styles/atom-parinfer.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor.indent-mode-76f60::shadow span.punctuation.section.end.trailing.clojure` => `atom-text-editor.indent-mode-76f60.editor span.syntax--punctuation.syntax--section.syntax--end.syntax--trailing.syntax--clojure`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by oakmac** [comment]
Thanks for the report :+1: 

This should be fixed with v1.17.0
