### ISSUE TITLE
Use Parinfer 2.0.0

### ISSUE THREAD

**Issue by shaunlebron** [oakmac/atom-parinfer#76]
2.0.0 has been out for 7 months!  Integration depends on https://github.com/oakmac/atom-parinfer/issues/66

**Comment by oakmac** [comment]
I don't like how Parinfer 2.0.0 can leave the user in an "imbalanced paren state" during Indent Mode.

**Comment by shaunlebron** [comment]
We have to choose between two evils:

1. Break inline expressions (Parinfer 1.x)
2. Highlight mistmatched inline parens (Pariner 2.x)

You prefer the first option?

**Comment by shaunlebron** [comment]
To reiterate the offending case:

```clj
(let [{:keys } foo])
          ; ^ insert a "[" here

;; Parinfer 1.x
(let [{:keys [ foo]})

;; Parinfer 2.x
(let [{:keys [} foo])
            ; ^ highlighted red until you finish typing the "]"
```

**Comment by oakmac** [comment]
I consider the Parinfer 2.x behavior broken here because it leaves the expression in an imbalanced state. Guaranteed paren matching is an essential feature of Indent Mode IMO.

In this particular example, it would be smart if Parinfer understood that map literals in Clojure must always have even forms. It could work like the following (with the pipe character `|` as the cursor):

```clj
(let [{:keys |} foo])
           ; ^ insert a "[" here

;; Smart Parinfer Behavior
(let [{:keys [|]} foo])
```

Perhaps Parinfer could have a few optional flags that make it more convenient to work with Clojure (which I suspect is 99% of it's modern application).

**Comment by shaunlebron** [comment]
The problem isn't specific to curly forms:

```clj
(foo [bar |] baz ... )
        ; ^ insert a "(" here
```

What would you prefer to happen in this case?

**Comment by oakmac** [comment]
```clj
(foo [bar |] baz ... )
        ; ^ insert a "(" here

;; expected
(foo [bar (|)] baz ... )
```

**Comment by shaunlebron** [comment]
Adding this rule affects the reverse case.  For example, what would you expect here?

```clj
(foo [bar (| baz ... )])
         ; ^ insert a "]" here

;; expected?
(foo [bar ()]| baz ... )
```

So the question is ultimately—what should we do with unmatched close-parens?

- Parinfer 1.x removes them indiscriminately, causing the problem we are trying to solve.
- Parinfer 2.x suspends and highlights them when they are seen (when not EOL).
- Oakinfer (from your expected result) would infer close-parens behind it.

My feeling is to stick with original intention of Indent Mode—to only infer parens based on indentation, and to not pretend to know what we're doing when indentation can no longer inform how we balance the user's code.

Option 3 seems to be a can of worms.

**Comment by oakmac** [comment]
:+1: for "Oakinfer" :rofl:

I prefer Parinfer 1.x behavior for the case you describe:

```clj
(foo [bar (| baz ... )])
         ; ^ insert a "]" here

;; Oakinfer expectation
(foo [bar (| baz ... )])
         ; ie: no change
```

This is not captured in the text above, but I also expect to see the editor show the key that was pressed briefly, then remove it (this is current behavior, btw).

The important distinction here is that the user is entering a **closing** paren that does not match. When using Parinfer, you think primarily in terms of open parens, and let Parinfer automatically handle closing parens.

**Comment by shaunlebron** [comment]
Thinking about implementation—Oakinfer would have to use the cursor position, since Parinfer receives no information about the most recent edit:

```clj
;; case 1 (original)
(foo [bar (]| baz ...
         ; ^ unmatched "]" detected on LEFT side  => remove

;; expected output
(foo [bar (| baz ...
```

```clj
;; case 2 (new)
(foo [bar (|] baz ...
          ; ^ unmatched "]" detected on RIGHT side  => infer parens behind it

;; expected output
(foo [bar (|)] baz ...
```

- PRO: typing `(` or even pasting `(foo` will both perform a wrap as far as it can
- PRO: back-spacing a `)` will "barf" the expression without affecting others
- CON: cursor movement after insertion could throw off inference when debounced

I'll try implementing so we can mull it over in Atom 👍

**Comment by shaunlebron** [comment]
Tracking here: https://github.com/shaunlebron/parinfer/issues/131

**Comment by shaunlebron** [comment]
@Engelberg latest version is in atom-parinfer.  Smart Mode is behind an experimental flag under settings
