### ISSUE TITLE
Is there a way to run this without atom if not all team members use atom?

### ISSUE THREAD

**Issue by langford** [oakmac/atom-parinfer#77]
Just wanted to check if there was something you knew of that allowed running this as a formatter in lein or something else.

**Comment by oakmac** [comment]
There is currently not a command line tool that I am aware of to "mass apply" Paren Mode to files, although I suspect it would not be too difficult to write one.

This unimplemented feature issue is related: https://github.com/oakmac/atom-parinfer/issues/21

Out of curiosity, what editors are your other team members using? Does a Parinfer plugin exist for them?

cc @shaunlebron

**Comment by shaunlebron** [comment]
@langford I can put together a Parinfer formatter that teams can run on their code base before committing, or to fail the CI if not formatted.  Is this what you're asking?

**Comment by langford** [comment]
That would work for our purposes. Just trying to not blow up the codebase
with diffs from everyone using their own formatter and committing.

   --Michael



--
Michael Langford
http://www.RowdyLabs.com

**Comment by shaunlebron** [comment]
tracking here: https://github.com/shaunlebron/parinfer/issues/132

**Comment by oakmac** [comment]
@langford FYI - https://github.com/shaunlebron/parlinter is now available :)

**Comment by shaunlebron** [comment]
@langford - I left you out of the loop for some reason when building it.  Let me know if it fits your needs, feedback appreciated!

**Comment by langford** [comment]
I am thankful. I was going to preview it with the person who uses
parafinier tomorrow afternoon.



--
Michael Langford
http://www.RowdyLabs.com
