### ISSUE TITLE
Smart Mode - divert to Indent Mode when text is selected

### ISSUE THREAD

**Issue by shaunlebron** [oakmac/atom-parinfer#87]
This feels to me like the best way to allow correcting the indentation of pasted code without causing indentation shifts of subsequent lines.

I can add more context later, but I think the status bar should say "Parinfer: Indent" when text is selected?

**Comment by oakmac** [comment]
Should custom pasting behavior be specified in the Parinfer library?

**Comment by shaunlebron** [comment]
ah, we can add an option for `selection`, and do it that way

**Comment by shaunlebron** [comment]
good call 👍 .  moving here: https://github.com/shaunlebron/parinfer/issues/167
