### ISSUE TITLE
Other multi-edit operations interfere with parinfer smart mode

### ISSUE THREAD

**Issue by seancorfield** [oakmac/atom-parinfer#94]
Paredit forward slurp is the most consistent example: if you have a multi-line s-exp and you do forward slurp in the first line, parinfer seems to get confused -- or does battle with paredit? -- about the intended structure and/or indentation of the code on the subsequent lines in the s-exp.

If you switch to paren mode before slurping, that always works. It's only when smart mode is enabled that paredit operations cause problems.

**Comment by shaunlebron** [comment]
@seancorfield trying to recreate this problem.  do you have examples?

I tried what you wrote:

![slurp](https://user-images.githubusercontent.com/116838/34926975-a6a3f6fe-f978-11e7-8f6d-b7c8bd0ab78d.gif)

**Comment by seancorfield** [comment]
Yeah, you need a more complex expression. I'll see if I run across it this week during work and try to pull together a repro case.

**Comment by seancorfield** [comment]
Here's a case that doesn't work as expected:
```
{:foo {:a 1}
 :bar {:x 1
       :y 2
       :z 3}
 :quux 42}
```
Double-click `bar` and start typing to replace it with a longer keyword:
```
   {:foo {:a 1}
    :long {:x 1}
          :y 2
          :z 3
    :quux 42}
```
That's not what I would expect.

**Comment by shaunlebron** [comment]
@seancorfield thanks for the example!  I tried it in the new version (1.21.0) and it seems to not have this problem anymore:

![fixed](https://user-images.githubusercontent.com/116838/35774732-67fcc08c-093d-11e8-8575-a0c8a54eada5.gif)

**Comment by seancorfield** [comment]
Sounds like you fixed it and since I don't use Atom anymore, I'm closing this. Thank you!
